version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

      - run: npm test

  deploy-auto:
    docker:
      - image: buildpack-deps:trusty
    environment:
      AUTO_HEROKU_APP_NAME: 'auto-introspection-api'
    steps:
      - checkout
      - run:
          name: Deploy auto environment to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$AUTO_HEROKU_APP_NAME.git master

  smoke-test:
    docker:
      - image: buildpack-deps:trusty
    environment:
      AUTO_HEROKU_APP_NAME: 'auto-introspection-api'
    steps:
      - run: sleep 60
      - run:
          name: Server smoke test
          command: curl -f https://$AUTO_HEROKU_APP_NAME.herokuapp.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-auto:
          requires:
            - build
      - smoke-test:
          requires:
            - deploy-auto
